default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: pw1234
  pool: 5

development:
  <<: *default
  database: test-a_dev_db


test:
  <<: *default
  database: test-a_test_db
